version: '3'

services:
  client:
    build:
      context: client/
    tty: true
  librarian:
    build:
      context: librarian/
    tty: true
    volumes:
      - type: bind
        source: "./packages"
        target: "/opt/app/packages"
